# Generated by Django 5.2.7 on 2025-10-21 16:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('database', '__first__'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Discussion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post', models.TextField(blank=True, null=True)),
                ('date_posted', models.DateTimeField(auto_now_add=True, null=True)),
                ('posted_by', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('selected_perfume', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='database.perfume')),
            ],
        ),
        migrations.CreateModel(
            name='ProposedSources',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('info', models.TextField(blank=True, null=True)),
                ('tag', models.TextField(blank=True, null=True)),
                ('source_url', models.CharField(blank=True, null=True)),
                ('date_posted', models.DateTimeField(auto_now_add=True)),
                ('posted_by', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('selected_perfume', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='database.perfume')),
            ],
        ),
    ]
