# Generated by Django 5.2.8 on 2025-11-24 20:47

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='proposedsources',
            name='availability_checklist',
            field=models.ManyToManyField(blank=True, related_name='verified_availability', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='proposedsources',
            name='notes_checklist',
            field=models.ManyToManyField(blank=True, related_name='verified_notes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='proposedsources',
            name='year_of_release_checklist',
            field=models.ManyToManyField(blank=True, related_name='verified_year', to=settings.AUTH_USER_MODEL),
        ),
    ]
