# Generated by Django 5.2.8 on 2025-11-24 20:57

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0002_proposedsources_availability_checklist_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proposedsources',
            name='tag',
        ),
        migrations.AddField(
            model_name='proposedsources',
            name='tags',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=500), blank=True, null=True, size=None),
        ),
    ]
