# Generated by Django 5.2.7 on 2025-10-21 16:32

import django.contrib.postgres.fields
import django.core.validators
import django.db.models.deletion
import django_countries.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BottleDesigner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('designer_image', models.ImageField(blank=True, null=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, max_length=300, null=True)),
                ('houseWebsite', models.URLField(blank=True, null=True)),
                ('country', django_countries.fields.CountryField(max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='InvalidParfumes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField()),
            ],
        ),
        migrations.CreateModel(
            name='NoteCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ParentCompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('company_image', models.CharField(blank=True, null=True)),
                ('parent_company_website', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PendingPerfumes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField()),
            ],
        ),
        migrations.CreateModel(
            name='ValidParfumes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField()),
            ],
        ),
        migrations.CreateModel(
            name='FragranceCollection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('collection', models.CharField(blank=True, max_length=40, null=True)),
                ('brand', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='database.brand')),
            ],
        ),
        migrations.CreateModel(
            name='FragranceNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('proposed_by', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='accounts.userprofile')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='database.notecategory')),
            ],
        ),
        migrations.AddField(
            model_name='brand',
            name='parentCompany',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='database.parentcompany'),
        ),
        migrations.CreateModel(
            name='Perfume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('perfume', models.CharField(blank=True, max_length=40, null=True)),
                ('brand_other', models.CharField(blank=True, max_length=40, null=True)),
                ('perfume_image', models.ImageField(blank=True, null=True, upload_to='')),
                ('parent_company_other', models.CharField(blank=True, max_length=40, null=True)),
                ('perfumer', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=500), blank=True, null=True, size=None)),
                ('new_perfumer', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=500), blank=True, null=True, size=None)),
                ('notes', django.contrib.postgres.fields.JSONField(blank=True, default=dict)),
                ('release_year', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1900), django.core.validators.MaxValueValidator(2100)])),
                ('gender', models.CharField(blank=True, max_length=15, null=True)),
                ('availability', models.BooleanField(blank=True, null=True)),
                ('is_limited', models.BooleanField(blank=True, null=True)),
                ('is_varient', models.BooleanField(blank=True, null=True)),
                ('is_collectors', models.BooleanField(blank=True, null=True)),
                ('interesting_facts', models.TextField(blank=True, null=True)),
                ('sources', models.CharField(blank=True, null=True)),
                ('additional_information', models.TextField(blank=True, null=True)),
                ('youtube_link', models.URLField(blank=True, null=True)),
                ('additional_link', models.URLField(blank=True, null=True)),
                ('status', models.CharField(blank=True, null=True)),
                ('date_posted', models.DateTimeField(auto_now_add=True, null=True)),
                ('bottle_designer', models.OneToOneField(blank=True, max_length=70, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('brand', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='database.brand')),
                ('collectors_original_perfume', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='database.perfume')),
                ('confirmed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('fragrance_collection', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='database.fragrancecollection')),
                ('parent_company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='database.parentcompany')),
                ('pending', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='database.pendingperfumes')),
                ('photo_subscribers', models.ManyToManyField(blank=True, related_name='photo_subscribers', to='accounts.userprofile')),
                ('proposed_by', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('rejected', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='database.invalidparfumes')),
                ('rejected_by', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('review_subscribers', models.ManyToManyField(blank=True, related_name='review_subscribers', to='accounts.userprofile')),
                ('statement_subscribers', models.ManyToManyField(blank=True, related_name='statement_subscribers', to='accounts.userprofile')),
                ('varient_original_perfume', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='database.perfume')),
                ('confirmed', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='database.validparfumes')),
            ],
        ),
        migrations.CreateModel(
            name='FragranceClassification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('occasion', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=500), blank=True, null=True, size=None)),
                ('season', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=500), blank=True, null=True, size=None)),
                ('style', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=500), blank=True, null=True, size=None)),
                ('type', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=500), blank=True, null=True, size=None)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='accounts.userprofile')),
                ('perfume', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='database.perfume')),
            ],
        ),
        migrations.CreateModel(
            name='EditedPerfume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('edited_perfume', models.CharField(blank=True, max_length=40, null=True)),
                ('edited_brand_other', models.CharField(blank=True, max_length=50, null=True)),
                ('edited_release_data', models.DateField(blank=True, null=True)),
                ('edited_gender', models.CharField(blank=True, max_length=15, null=True)),
                ('edited_availability', models.CharField(blank=True, null=True)),
                ('edited_limited', models.BooleanField(blank=True, null=True)),
                ('edited_varient', models.BooleanField(blank=True, null=True)),
                ('edited_collectors', models.BooleanField(blank=True, null=True)),
                ('edited_interesting_facts', models.TextField(blank=True, null=True)),
                ('edited_sources', models.CharField(blank=True, null=True)),
                ('edited_additional_information', models.TextField(blank=True, null=True)),
                ('edited_youtube_link', models.CharField(blank=True, null=True)),
                ('edited_additional_link', models.CharField(blank=True, null=True)),
                ('edited_status', models.CharField(blank=True, null=True)),
                ('confirmed_by', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('edited_brand', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='database.brand')),
                ('edited_by', models.OneToOneField(blank=True, default=2, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('rejected_by', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('selected_perfume', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='database.perfume')),
            ],
        ),
        migrations.CreateModel(
            name='Perfumer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('perfumer_image', models.ImageField(blank=True, null=True, upload_to='')),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='database.brand')),
            ],
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scent_rating', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('sillage_rating', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('longevity_rating', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('bottle_rating', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('price_rating', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('time_rated', models.DateTimeField(auto_now_add=True)),
                ('rated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='accounts.userprofile')),
                ('rated_perfume', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='database.perfume')),
            ],
        ),
        migrations.CreateModel(
            name='Reviews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField()),
                ('review', models.TextField(blank=True, null=True)),
                ('scent_associations', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(verbose_name=20), blank=True, null=True, size=None)),
                ('date_posted', models.DateField(auto_now_add=True)),
                ('awards', models.ManyToManyField(blank=True, related_name='+', to='accounts.userprofile')),
                ('down_votes', models.ManyToManyField(blank=True, related_name='+', to='accounts.userprofile')),
                ('posted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='accounts.userprofile')),
                ('reviewed_perfume', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='database.perfume')),
                ('up_votes', models.ManyToManyField(blank=True, related_name='+', to='accounts.userprofile')),
            ],
        ),
        migrations.CreateModel(
            name='Statements',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statement', models.TextField(blank=True, null=True)),
                ('scent_associations', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(verbose_name=20), blank=True, null=True, size=None)),
                ('date_posted', models.DateField(auto_now_add=True)),
                ('awards', models.ManyToManyField(blank=True, related_name='+', to='accounts.userprofile')),
                ('posted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='accounts.userprofile')),
                ('statement_perfume', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='database.perfume')),
            ],
        ),
        migrations.CreateModel(
            name='TestPerfume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('status_key', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='database.pendingperfumes')),
            ],
        ),
        migrations.CreateModel(
            name='UserCollection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currently_own', models.ManyToManyField(blank=True, related_name='currently_own', to='database.perfume')),
                ('decants', models.ManyToManyField(blank=True, related_name='decants', to='database.perfume')),
                ('owned_before', models.ManyToManyField(blank=True, related_name='owned_before', to='database.perfume')),
                ('tested', models.ManyToManyField(blank=True, related_name='tested', to='database.perfume')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('watching', models.ManyToManyField(blank=True, related_name='watching', to='database.perfume')),
                ('wish_list', models.ManyToManyField(blank=True, related_name='wish_list', to='database.perfume')),
            ],
        ),
        migrations.CreateModel(
            name='CustomCollection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('collection_name', models.CharField(blank=True, max_length=50, null=True)),
                ('description', models.TextField(blank=True, max_length=200, null=True)),
                ('collection_icon', models.ImageField(blank=True, null=True, upload_to='')),
                ('perfumes', models.ManyToManyField(blank=True, related_name='perfumes', to='database.perfume')),
                ('user_collection', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='database.usercollection')),
            ],
        ),
    ]
