# Generated by Django 5.2.8 on 2025-11-12 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fragrancecollection',
            old_name='collection',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='perfume',
            old_name='new_perfumer',
            new_name='bottle_designer_other',
        ),
        migrations.RenameField(
            model_name='perfume',
            old_name='perfumer',
            new_name='perfumers_other',
        ),
        migrations.AddField(
            model_name='perfume',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='perfume',
            name='fragrance_collection_other',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AddField(
            model_name='perfume',
            name='limited_original_perfume',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AddField(
            model_name='perfume',
            name='perfumers',
            field=models.ManyToManyField(blank=True, to='database.perfumer'),
        ),
        migrations.RemoveField(
            model_name='perfume',
            name='bottle_designer',
        ),
        migrations.AlterField(
            model_name='perfume',
            name='collectors_original_perfume',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='perfume',
            name='notes',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='perfume',
            name='perfume',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='perfume',
            name='varient_original_perfume',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AddField(
            model_name='perfume',
            name='bottle_designer',
            field=models.ManyToManyField(blank=True, to='database.bottledesigner'),
        ),
    ]
