# Generated by Django 5.2.8 on 2025-11-12 03:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0002_rename_collection_fragrancecollection_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perfume',
            name='notes',
        ),
    ]
