# Generated by Django 5.2.8 on 2025-11-12 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0003_remove_perfume_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfume',
            name='notes',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
