# Generated by Django 5.2.8 on 2025-11-12 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0004_perfume_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfume',
            name='views',
            field=models.IntegerField(default=0),
        ),
    ]
