# Generated by Django 5.2.8 on 2025-11-20 03:47

import django.contrib.postgres.fields
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0005_perfume_views'),
    ]

    operations = [
        migrations.RenameField(
            model_name='editedperfume',
            old_name='edited_additional_information',
            new_name='additional_information',
        ),
        migrations.RenameField(
            model_name='editedperfume',
            old_name='edited_collectors',
            new_name='availability',
        ),
        migrations.RenameField(
            model_name='editedperfume',
            old_name='edited_brand',
            new_name='brand',
        ),
        migrations.RenameField(
            model_name='editedperfume',
            old_name='edited_brand_other',
            new_name='brand_other',
        ),
        migrations.RenameField(
            model_name='editedperfume',
            old_name='edited_interesting_facts',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='editedperfume',
            old_name='edited_gender',
            new_name='gender',
        ),
        migrations.RenameField(
            model_name='editedperfume',
            old_name='edited_limited',
            new_name='is_collectors',
        ),
        migrations.RenameField(
            model_name='editedperfume',
            old_name='edited_varient',
            new_name='is_limited',
        ),
        migrations.RenameField(
            model_name='editedperfume',
            old_name='edited_perfume',
            new_name='parent_company_other',
        ),
        migrations.RenameField(
            model_name='editedperfume',
            old_name='edited_additional_link',
            new_name='sources',
        ),
        migrations.RenameField(
            model_name='editedperfume',
            old_name='edited_availability',
            new_name='status',
        ),
        migrations.RemoveField(
            model_name='editedperfume',
            name='edited_release_data',
        ),
        migrations.RemoveField(
            model_name='editedperfume',
            name='edited_sources',
        ),
        migrations.RemoveField(
            model_name='editedperfume',
            name='edited_youtube_link',
        ),
        migrations.AddField(
            model_name='editedperfume',
            name='additional_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='editedperfume',
            name='bottle_designer',
            field=models.ManyToManyField(blank=True, to='database.bottledesigner'),
        ),
        migrations.AddField(
            model_name='editedperfume',
            name='bottle_designer_other',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=500), blank=True, null=True, size=None),
        ),
        migrations.AddField(
            model_name='editedperfume',
            name='collectors_original_perfume',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AddField(
            model_name='editedperfume',
            name='edited_release_year',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1900), django.core.validators.MaxValueValidator(2100)]),
        ),
        migrations.AddField(
            model_name='editedperfume',
            name='fragrance_collection',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='database.fragrancecollection'),
        ),
        migrations.AddField(
            model_name='editedperfume',
            name='fragrance_collection_other',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AddField(
            model_name='editedperfume',
            name='interesting_facts',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='editedperfume',
            name='is_varient',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='editedperfume',
            name='limited_original_perfume',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AddField(
            model_name='editedperfume',
            name='notes',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='editedperfume',
            name='parent_company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='database.parentcompany'),
        ),
        migrations.AddField(
            model_name='editedperfume',
            name='perfume',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='editedperfume',
            name='perfumers',
            field=models.ManyToManyField(blank=True, to='database.perfumer'),
        ),
        migrations.AddField(
            model_name='editedperfume',
            name='perfumers_other',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=500), blank=True, null=True, size=None),
        ),
        migrations.AddField(
            model_name='editedperfume',
            name='varient_original_perfume',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AddField(
            model_name='editedperfume',
            name='youtube_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
