# Generated by Django 5.2.8 on 2025-11-20 05:22

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0006_rename_edited_additional_information_editedperfume_additional_information_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='editedperfume',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
