# Generated by Django 6.0.1 on 2026-02-17 21:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0009_remove_perfume_sources_fragrancesource'),
    ]

    operations = [
        migrations.RenameField(
            model_name='editedperfume',
            old_name='edited_release_year',
            new_name='release_year',
        ),
    ]
